from pathlib import Path
import json,re,math,hashlib,zipfile
root=Path(__file__).parent
script=(root/'script.txt').read_text()
title='Why You Want Success But Keep Choosing Comfort'
# Nine distinct editorial illustrations per sheet; the order is row-major.
sheets=[
('The life you imagine','You say you want a better life.',[
'Character studying a distant sunrise.','Coin jar beside modest workbench.','Character beside an open doorway.','Character standing upright before mirror.','Shoes ready beside a small clock.','Character building a simple wooden object.','Character approaching a dumbbell.','Character practicing with a sketchbook.','Sleepy character reaching toward bedside alarm.']),
('The everyday detour','You know you should work.',[
'Unfinished laptop beside glowing phone.','Character choosing phone over work.','Unused exercise mat beside sofa.','Character postponing an unopened project.','Character tidying an already-clean shelf.','Character watching a blank video screen.','Character stacking unused planning notebooks.','Daylight fading behind seated character.','Repeated blank calendar pages beside bed.']),
('Comfortable moments accumulate',"Because here's the strange part.",[
'Character choosing one soft cushion.','Several cushions becoming a enclosing wall.','Character inside a comfortable cushion enclosure.','Character facing an assignment notebook.','Character before an unfinished workbench.','Character beside untouched workout equipment.','Two characters avoiding eye contact.','Character outside an unopened project doorway.','Character noticing an obvious first step.']),
('Busy is not progress',"There wasn't some huge mystery.",[
'Character buried behind research books.','Character juggling blank productivity screens.','Character watching motivational silhouette on screen.','Character hesitating before an empty desk.','Character reaching for a phone.','Character making an elaborate coffee.','Character arranging blank folders precisely.','Character answering an overflowing message tray.','Untouched important notebook beneath busywork pile.']),
('Now versus later','Imagine you have two choices.',[
'Character between small treat and distant workshop.','Phone offering a tiny immediate spark.','Character lifting a modest dumbbell.','Character watching a blank entertainment screen.','Character practicing a difficult craft.','Character receiving a small shopping parcel.','Character placing one coin into savings jar.','Character resting under a soft blanket.','Character approaching a difficult doorway.']),
('The present has an advantage',"But your future can't give you a reward yet.",[
'Character reaching toward a distant unmarked horizon.','Solid nearby chair beside faint distant doorway.','Character comparing tangible phone and distant workshop.','Character sincerely looking toward personal goal.','Character holding ambition notebook beside comfortable chair.','Character balancing present need and future intention.','Character facing two choices without villain imagery.','Character beside unfinished bridge toward tomorrow.','Character taking one tentative bridge step.']),
('Practicing avoidance',"And there's another problem.",[
'Character walking a familiar circular path.','Character leaving a difficult desk.','Bored character immediately reaching toward phone.','Character abandoning a partly built object.','Repeated shallow footprints around comfort chair.','Character automatically opening phone beside desk.','Character looking puzzled at own repeated footprints.','Character holding goal notebook before difficult staircase.','Character pausing on first stair without fleeing.']),
('Ambition meets environment','You can have huge ambitions...',[
'Character viewing large aspiration through small doorway.','Character stepping away from imperfect first attempt.','Character sheltering behind a small safety screen.','Tempting phone and snacks within arm reach.','Character under a cloud of blank thought bubbles.','Character facing a distorted self-reflection.','Character carrying an unnecessarily heavy burden.','Comfort chair directly beside unfinished work.','Character surveying a room designed for distraction.']),
('Easy pleasure, invisible progress','Think about your phone.',[
'Phone immediately beside resting hand.','Character tapping blank entertainment tiles.','Character before an unfamiliar lesson notebook.','Character struggling with a simple practice puzzle.','Character correcting an imperfect sketch.','Small unfinished practice pieces accumulating.','Character practicing alone without an audience.','Tiny sprout beside an ordinary practice desk.','Character comparing soft chair and challenging workbench.']),
('Make the right choice easier',"And this is why discipline isn't simply about becoming stronger.",[
'Character removing an obstacle from desk path.','Phone placed on distant room shelf.','Character setting distraction device inside closed drawer.','Workout clothing neatly prepared beside shoes.','Open book on uncluttered desk.','Open project notebook ready before bedtime.','Single accessible tool beside first workpiece.','Exhausted character lowering an imaginary shield.','Character cautiously peeking beyond a protective curtain.']),
('Comfort as protection','Because what happens if you actually try?',[
'Character opening a small empty shop.','Character filming beside an empty viewing bench.','Character beside weights and imperfect mirror reflection.','Character facing a difficult exam notebook.','Character uncovering an unfinished personal creation.','Character holding a shield before a starting doorway.','Untouched tools safely wrapped in a box.','Imagined finished sculpture beside covered real clay.','Character inside soft enclosure with open exit.']),
('The relief cycle','And this creates a strange cycle.',[
'Character turning away from difficult work.','Character relaxing immediately in soft chair.','Character retracing familiar avoidance footprints.','Character noticing unfinished notebook with lowered shoulders.','Character making a fresh promise beside sunrise.','Character imagining confident future reflection.','Character encountering the same difficult workbench.','Character returning toward familiar comfort chair.','Character noticing a second previously unused path.']),
('Start smaller',"You don't need to suddenly become a completely disciplined person.",[
'Character lowering an oversized routine checklist.','Character ignoring dramatic pre-dawn alarm ritual.','One small tool beside a manageable workpiece.','Phone set aside beside short-work timer.','Character sitting down for one small work session.','Character putting on exercise shoes.','Character opening one project notebook.','Character making a single imperfect practice mark.','Character staying calmly beside an unfinished task.']),
('Evidence and self-trust','Because every time you do that...',[
'Character placing a small finished piece on shelf.','Character completing a modest desk task.','Character returning shoes after a workout.','Character setting phone down intentionally.','Several ordinary completed pieces neatly accumulating.','Character meeting own reflection with relaxed posture.','Character lowering imaginary punishment weight.','Character stepping past competing blank thought bubbles.','Character calmly reaching for next prepared tool.']),
('What you repeat becomes your life','Because the truth is...',[
'Character standing on repeated small stepping stones.','Character watching a distant goal without moving.','Repeated phone-reaching footprints beside comfortable chair.','Character repeatedly circling a safe enclosure.','Character leaving unfinished attempts at doorway.','Character resting peacefully beneath a tree.','Character enjoying a simple shared game.','Character returning from rest to workbench.','Comfort chair separated from an open working doorway.']),
('Ordinary choices, different future','Because sometimes...',[
'Soft shortcut ending before a difficult barrier.','Steeper path opening toward a calm valley.','Character studying beside an inactive phone.','Character saving a coin beside tempting parcel.','Character practicing rather than watching a screen.','Character entering a modest exercise space.','Two characters beginning an honest conversation.','Character starting an imperfect handmade object.','Many small stepping stones forming a workable path.']),
('Choose what matters','So the next time you catch yourself saying,',[
'Character noticing hand reaching for phone.','Character pausing between comfort chair and workbench.','Character looking toward personally meaningful doorway.','Soft cushion resting beside an unfinished task.','Character gently moving chair away from threshold.','Character protecting a small peaceful resting corner.','Character balancing rest and purposeful effort.','Character accepting an imperfect difficult first step.','Character approaching a slightly open doorway.']),
('Build your future today','Because the life you want...',[
'Character stepping toward waiting exercise shoes.','Character practicing an unfamiliar skill slowly.','Character uncovering a project despite uncertainty.','Two characters moving chairs toward honest conversation.','Character making an imperfect first clay shape.','Character repeating small craft movements alone.','Character choosing a different fork from familiar path.','Character laying one stone toward sunrise.','Character standing calmly beside an open horizon.'])]
base=('Create a 3840x2160 landscape contact sheet: 3x3 grid, nine 16:9 panels, thin black dividers. '
'Use attached canonical stickman reference: round white head, charcoal hoodie, rust-orange lining. '
'Editorial ink doodle, warm paper #F7F4EE, rust wash #C8623C. '
'Odd panels: subject right, left 40% blank; even panels: reverse. '
'Every panel: bottom 20% clear. No words, numbers, logos or diagrams. Row-major panels:\n')
prompts=[]
anchors=[]
for i,(name,anchor,panels) in enumerate(sheets,1):
    prompt=base+'\n'.join(f'{j}. {p}' for j,p in enumerate(panels,1))
    assert len(prompt.split())<150,(i,len(prompt.split()))
    prompts.append({'id':f'sheet-{i:02}','filename':f'sheet-{i:02}.png','name':name,'prompt':prompt,'word_count':len(prompt.split())})
    pos=script.find(anchor)
    assert pos>=0,anchor
    anchors.append(pos)
assert anchors==sorted(anchors)
thumb=('Create one 1920x1080 landscape editorial thumbnail, not a grid. Use the attached canonical stickman: '
'round white head, charcoal hoodie with rust-orange lining. Warm paper #F7F4EE, expressive charcoal ink, '
'rust-orange watercolor #C8623C, tiny restrained gold accent. Right side: the character sinks into a soft '
'armchair whose cushions subtly encircle them; one hand reaches toward an open doorway and a single '
'upward step, but a phone holds their attention. Psychological tension, not ridicule. One clear focal '
'character, bold silhouette, minimal props, strong readability at mobile size. Leave left 40% completely '
'clean for manually added headline “COMFORT IS COSTING YOU”. Generate no text, letters, logos, arrows, '
'watermarks or extra characters. Keep all key elements away from outer edges.')
assert len(thumb.split())<150
md=f'# Image prompt bundle\n\nEpisode: {title}\n\n## Instructions\n\nAttach the canonical stickman reference to EVERY request. Generate one image per prompt. Each contact sheet is a single 3x3 landscape image, not nine separate files. Save sheet-01.png through sheet-18.png and thumbnail.png. Numbering below is prompt guidance only: no numbers printed in artwork. Upload originals at maximum available resolution, not chat screenshots. If 3840x2160 is unsupported, use the largest native 16:9 output; do not claim it is native 4K.\n\nThe 18-sheet / 162-panel budget is provisional: 1,975 script words at 140 words/minute gives about 14.1 minutes. Actual processed narration may require a different count using ceil(duration_seconds / 60 * 1.25). These prompts are the complete initial bundle, not a guarantee of the final count.\n\nOnly artwork is generated: all labels, diagrams, counters and captions are added during motion production. Odd/even composition supports paired reversals within each semantic sequence. Rest is not portrayed as a moral failure. Reuse the supplied canonical subscribe end card; do not generate a replacement.\n'
for p in prompts:
    md+=f'\n## {p["id"]} — {p["name"]}\n\n```text\n{p["prompt"]}\n```\n'
md+=f'\n## thumbnail.png\n\n```text\n{thumb}\n```\n'
(root/'image-prompts.md').write_text(md)
(root/'image-jobs.json').write_text(json.dumps({'status':'prompts_only_not_generated','contact_sheets':prompts,'thumbnail':{'filename':'thumbnail.png','prompt':thumb}},indent=2))
engines=['paths','feed','stack','search','split','timeline','loop','balance','stairs','focus','window','loop','clock','stack','paths','stairs','switch','finish']
scenes=[]
inventory=[]
for i,(name,anchor,panels) in enumerate(sheets):
    ending=anchors[i+1] if i+1<len(sheets) else len(script)
    phrase=script[anchors[i]:ending].strip()
    scene={'id':f'chapter-{i+1:02}','start':None,'end':None,'art':[f'S{i+1:02}-P{j:02}' for j in range(1,10)],'kind':engines[i],'title':name,'labels':[],'cues':[],'dark':i in (10,11,16),'layout':'planned paired illustration/graphic columns','chapter':name,'feature':i in (4,6,11,17),'phrase':phrase,'status':'semantic draft; no aligned timing','opening_phrase':anchor,'reuse_rationale':'Panel budget is not a cut quota; adapt scene subdivision and reuse after narration alignment.'}
    scenes.append(scene)
    for j,desc in enumerate(panels,1):
        inventory.append({'panel_id':f'S{i+1:02}-P{j:02}','source':f'sheet-{i+1:02}.png','row':(j-1)//3+1,'column':(j-1)%3+1,'illustration':desc,'empty_side':'left' if j%2 else 'right','chapter':name,'spoken_section_anchor':anchor,'cue_start':None,'cue_end':None,'planned_engine':engines[i],'asset_status':'awaiting_user_image','use_status':'planned_not_yet_used'})
assert '\n\n'.join(s['phrase'] for s in scenes).split()==script.split(),'Narration coverage mismatch'
(root/'scene-plan.draft.json').write_text(json.dumps({'status':'unaligned_semantic_draft','fps':30,'width':1920,'height':1080,'scenes':scenes},indent=2))
(root/'panel-inventory.planned.json').write_text(json.dumps(inventory,indent=2))
seo=f'''# {title}\n\n## Description draft\nYou can genuinely want a better life and still choose what feels easiest right now. This Why We Become episode explores immediate rewards, avoidance, environment design, fear of failure, and the small repeated choices that build self-trust. Comfort is not the enemy: the question is whether temporary relief is making your decisions for you.\n\nThink deeper. Live better. Become more.\n\n## Chapters\nNot timestamped: processed narration and verified alignment are required. Do not publish estimated chapter times.\n'''+''.join(f'- {s["title"]}\n' for s in scenes)+'''\n## Tags\nWhy We Become, comfort zone, discipline, procrastination, fear of failure, habits, self trust, personal growth\n\n## Suggested pinned comment\nWhat is one small uncomfortable choice you can make today—not to punish yourself, but to move toward what matters to you?\n'''
(root/'seo.draft.md').write_text(seo)
checkpoint={'title':title,'status':'image-ready preproduction; no generated artwork, narration or render','script_words':1975,'script_sha256':hashlib.sha256(script.encode()).hexdigest(),'estimate_words_per_minute':140,'estimate_runtime_seconds':1975/140*60,'estimate_is_not_audio_duration':True,'provisional_sheets':18,'provisional_panels':162,'thumbnail_prompts':1,'final_sheet_rule':'ceil(final_processed_audio_seconds / 60 * 1.25)','narration':'not supplied or synthesized in this turn','timing':'all start/end/cue fields deliberately null','renderer':'not implemented','master':'not rendered','release':'not created','images':'user generates and uploads; no automatic image-generation calls','visibility':'existing repository remains private'}
(root/'production-checkpoint.json').write_text(json.dumps(checkpoint,indent=2))
(root/'README.md').write_text(f'''# {title}\n\nImage-ready preproduction checkpoint. Script wording preserved; only user message line-break markup normalized to newlines.\n\n## Files\n- script.txt — preserved narration\n- image-prompts.md — all 18 sheet prompts plus dedicated thumbnail\n- image-jobs.json — copy-ready prompt inventory\n- scene-plan.draft.json — 18 semantic chapter groupings, not timed renderer scenes\n- panel-inventory.planned.json — 162 planned cells, none claimed to exist\n- seo.draft.md — description and untimed chapter names\n- production-checkpoint.json — honest status\n- build_bundle.py — reproducible builder and validations\n\n## Ready / blocked\nThe artwork brief, semantic routing, panel inventory, and SEO draft are ready. Actual artwork extraction, masking/upscaling, narration processing, word alignment, timed scene subdivision, motion renderer, captioned samples, full master, visual QA and versioned release are not done.\n\nNo automatic image generation occurs here. Upload sheet-01.png through sheet-18.png and thumbnail.png. Keep the existing canonical subscribe end card. Align only after final audio processing. Recalculate the sheet count from real audio duration.\n\n## Safety / scope\nNo credentials, private instruction exports or signed asset URLs are included. Do not fabricate scientific numbers or curves; meters and paths are illustrative concepts. Hide future labels and never clamp cues to reveal early. Preserve speech and rest-friendly messaging.\n''')
(root/'.gitignore').write_text('.env\n.env.*\n*.log\n__pycache__/\nassets/\noutput/\n')
(root/'production-notes.md').write_text('''# Independent production preparation\n\n## Visual thesis\nImmediate comfort is a soft enclosure; a better future is an open doorway reached through ordinary small actions. Start observational, move through false productivity and immediate rewards, pivot to environment and protective avoidance, finish with self-trust. Do not shame healthy rest or illustrate success as a mansion/luxury stereotype.\n\n## Motion assignments\nUse split comparisons for present/later; paths for repeated choices; a node-by-node loop for discomfort → avoidance → relief → guilt → promise → renewed discomfort; a short-work timer only for the script’s ten-minute example; stack completed actions as evidence; switch between protective and enabling environments. All quantities must be script-supported; no fake empirical plots. Actual illustrations remain user-supplied.\n\n## Label / caption contract\nCreate typography in the renderer, never bake it into images. Keep a separate lower caption lane. Cue each label from verified speech. All draft timestamps are null. Final subtitles follow processed narration; no stretching audio to match artwork.\n\n## Audio preparation specification\nUse supplied narration if later uploaded. Preserve script wording. Process vocal cleanup and pause trimming before STT alignment; then never change timing without realignment. No audio has been synthesized or inspected. Provider endpoint and voice must be verified before an actual TTS request.\n\n## Next factual gates\n1. Inspect original images for correct grid, canonical character, clean subtitle band, no pseudo-text or repeated crops.\n2. Extract real boundaries and prepare masks/layers, then log all used or intentionally omitted panels.\n3. Finish narration, align words and scene cues, assign real start/end values.\n4. Build and inspect actual captioned frames and motion clips.\n5. Render 1920×1080, 30fps master; check duration within 0.5 seconds of audio, non-silent audio at -17.5 to -14.5 LUFS, non-empty subtitles, transitions and end card.\n6. Scan package and publish a new versioned release only for finished reviewed deliverables.\n''')
with zipfile.ZipFile('/data/success-comfort-image-ready.zip','w',zipfile.ZIP_DEFLATED) as z:
    for f in sorted(root.iterdir()):
        if f.is_file():z.write(f,arcname=f.name)
print(json.dumps({'sheet_prompts':len(prompts),'panels':len(inventory),'max_prompt_words':max(p['word_count'] for p in prompts),'thumbnail_words':len(thumb.split()),'script_words':len(re.findall(r"\b[\w]+(?:['’][\w]+)*\b",script)),'zip':'success-comfort-image-ready.zip'},indent=2))
